; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	arduino-libraries/Stepper@^1.1.3
	adafruit/Adafruit PCF8574@^1.1.2
	adafruit/Adafruit BusIO@^1.17.4
	thomasfredericks/Bounce2@^2.72
	madhephaestus/ESP32Servo@^3.1.3
	blackhack/LCD_I2C@^2.4.0
	256dpi/MQTT@^2.5.2
	adafruit/RTClib@^2.1.4
	olikraus/Ucglib@^1.5.2
	adafruit/Adafruit VL53L1X@^3.1.2
	pololu/VL53L1X@^1.3.1
